### ISSUE TITLE
Can't see channel icons

### ISSUE THREAD

**Issue by Stanymanman** [pgaubatz/TvplexendChannel.bundle#2]
Hi,

After testing yout channel on plex, it was impossible to see channel icons...

So I offer to you this solution at line 131 of your file "**init**.py" : 

base_url = urlparse(Prefs['url'])
thumb = base_url.scheme + '://' + '%s:%s@%s' % (Prefs['username'], Prefs['password'], base_url.netloc) + '/' + channel['icon_public_url']

I'm a newbie, so I don't if there is a better way, but it works !

**Comment by pgaubatz** [comment]
Hi,

thanks for reporting this issue.
Could you try 53efff7 and see if it fixes the problem?

Cheers,
Patrick
